apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: 	<arn_of_instance_role_of_worker_nodes>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: <arn_of_jenkins_user_that_needs_to_control_the_cluster>
      username: <jenkins_user_name>
      groups:
        - system:masters

