apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prayertimes-deployment-${TARGET_ROLE}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: prayertimes
        role: ${TARGET_ROLE}
    spec:
      containers:
      - name: prayertimes-container
        image: ysmaoui/prayer-times-service:${APP_VERSION}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
