kind: Service
apiVersion: v1
metadata:
  name: prayertimes-service
  labels:
    app: prayertimes
    role: ${TARGET_ROLE}
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: prayertimes
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 80